# Site settings
title: Govinda Raj
twitter_username: 511govindaraj
name: Govinda Raj
address: Bangalore, India

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/govindaraj511/
 - title: Quora
   url: https://www.quora.com/profile/Govinda-Raj-6
 - title: GitHub
   url: https://github.com/govinda-raj
 - title: StackOverflow
   url: https://stackoverflow.com/users/8120682/wolfie
 - title: Medium
   url: https://medium.com/@govinda_raj
 - title: Facebook
   url: https://www.facebook.com/511govindaraj
 

#Any buzzword skills you want to include
skills:
 - Spring Boot
 - Apache Kafka
 - MySQL
 - MongoDB
 - Kafka Stream
 - Kafka Connect
 - Google Cloud Platform
 - Redis
 - Docker
 - Mesos & Marathon
 - Kubernetics
 - React Native
 - TensorFlow

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://medium.com/@govinda_raj

#Work experience is required
roles:
 - title: Senior Software Engineer
   start: May 2019
   end: Current
   employer: ODCEM Pvt. Ltd.
   description: ODCEM is one of the largest customer experience management service provider. It has three products as Service Cloud, Feedback Cloud and Messaging Cloud. I work for Feedback Cloud, which helps brand to make their product better by taking feedback and providing analytics on top of that.
 - title: Software Engineer
   start: July 2017
   end: April 2019
   employer: Coviam
   description: Coviam was established as an digital innovative for the development of a number of software and legal-tech projects, and a rapidly growing, Indonessia-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Java, Block-chain, Data Analysis, a variety of Machine Learning techniques.
 - title: Software Trainee
   start: May 2016
   end: July 2016
   employer: ArcellorMittal
   description: ArcelorMittal S.A. is a Luxembourgish multinational steel manufacturing corporation headquartered in Luxembourg. It was formed in 2006 from the takeover and merger of Arcelor by Indian-owned Mittal Steel.
 

#Education is required
education:
 - level: Master of Technology (M.Tech)
   date: 2021
   subject: Data Science
   school: BITS Pillani Work Integrated, Bangalore
 - level: Bachelor of Technology (B.Tech)
   date: 2017
   subject: Computer Science
   school: The LNM Institute of Information Technology, Jaipur
 - level: Higher Secondary School
   date: 2012
   subject: Science
   school: St. Xaviers Jr/Sr School, Ramna, Bihar
 - level: Higher Primary School
   date: 2010
   subject: Science
   school: B.A.A.P. High School, Bara Chakia, Bihar


#List of interesting Github repo/projects to include - optional
github:
 - govinda-raj/Tweet-Analysis
 - govinda-raj/Tour-Planning
 - govinda-raj/e-commerce


#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/8120682/wolfie
   flairimageurl: https://i.stack.imgur.com/7jE9x.jpg

blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Spring Boot</strong>: The framework, I have worked on, from stating of my career. Having 3+ years of experience with the framework has made more confident and reliable for any kind of API driven projects. I have created several bug free APIs so far which has helped the company to grow like anything. My approach is generally TDD which is nothing but Test Driven Development which helps me a lot reduce bugs in code. <br/><br/>
   <strong>Apache Kafka</strong>: I am very profecient with the library because I really find it interesting. The way it has been developed to make it fault tolerent using multiple brokers, partitions, replicas; are remarkable. The way <strong>Apache Zookeeper</strong> handles kafka brokers and partitions by leader election, helps kafka alot. I have done several projects so far using kafka, kafka stream, kafka connect. For deployemnt of Stream application I used Mesos and Marathon.<br/><br/>
   <strong>Docker and GCP</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have enough experience of Google Cloud Platform and Docker.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including React Native, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
   As part of Nerdability. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://medium.com/@govinda_raj/">Govinda Raj's Blogs</a> (I am also a <a target='_blank' href="https://www.quora.com/profile/Govinda-Raj-6">Quoran</a>)